# Required
version: 2

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

build:
  os: ubuntu-24.04
  tools:
    python: "3.9"
