# Runs the testing matrix and code coverage

name: OSX

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # allows running manually
  workflow_dispatch:
jobs:

  build:
    strategy:
      matrix:
        os: [ macos-latest ]
        python-version: ["3.9"]

    runs-on: ${{ matrix.os }}

    steps:
      # check out the repo
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/prd.txt
          python -m pip install -r requirements/test.txt

      - name: Run tests
        run: python -m pytest --cov=fitsmap -vv --cov-report=xml:coverage.xml
