# Runs the testing matrix and code coverage

name: OSX

on:
  push:
    branches: [ "push-jwst-hotfixes", "master" ]
  pull_request:
    branches: [ "master" ]

  # allows running manually
  workflow_dispatch:
jobs:

  build:
    strategy:
      matrix:
        os: [ macos-latest ] #, windows-latest, macos-latest]
        python-version: ["3.8"] # TODO: decide how many versions to support

    runs-on: ${{ matrix.os }}

    steps:
      # check out the repo
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest pytest-cov codecov
          python -m pip install .

      - name: Run tests
        run: pytest --cov=fitsmap -vv